PWD := $(shell pwd)

all: clean
	python3 ./builder.py

clean:
	rm -rf ${PWD}/scalable
	rm -rf ${PWD}/8x8
	rm -rf ${PWD}/12x12
	rm -rf ${PWD}/16x16
	rm -rf ${PWD}/20x20
	rm -rf ${PWD}/24x24
	rm -rf ${PWD}/32x32
	rm -rf ${PWD}/48x48
	rm -rf ${PWD}/64x64/
	rm -rf ${PWD}/96x96
	rm -rf ${PWD}/128x128
	rm -rf ${PWD}/256x256
	rm -rf ${PWD}/512x512
